name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test_rust:
    name: Build and Test Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release
        working-directory: ic-response-verification-rs

      - name: Test
        run: cargo test --lib
        working-directory: ic-response-verification-rs

      - name: Lint
        run: cargo clippy
        working-directory: ic-response-verification-rs

      - name: Check Formatting
        run: cargo fmt --all -- --check
        working-directory: ic-response-verification-rs

  build_npm_package:
    name: Build NPM Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bazel
        uses: bazelbuild/setup-bazelisk@v2

      - name: Setup Bazel Cache
        uses: actions/cache@v3
        with:
          path: '~/.cache/bazel'
          key: bazel

      - name: Build
        run: bazel build //ic-response-verification-ts:lib

  check_commit_messages:
    name: Check Commit Messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Commitzen
        run: |
          python -m pip install --upgrade pip
          pip install -U Commitizen

      - name: Check Commit Messages
        run: cz check --rev-range c8ecbc19b8c4a482e55907d37554d66f2f2f9a8f..HEAD
